### ISSUE TITLE
The code has a error

### ISSUE THREAD

**Issue by stonecropa** [ValentinKoch/SVDNA#1]
![image](https://github.com/ValentinKoch/SVDNA/assets/114655828/e43dca56-7958-4536-977b-531dec921b1d)

**Comment by ValentinKoch** [comment]
Hi, could you send me a sample image that you are trying to process? Currently the method only works for grayscale images with one channel, it seems your image has 4 channels. Probably you would have to do SVDNA channelwise :)

**Comment by stonecropa** [comment]
@ValentinKoch  
Thanks. I have set it to channel 1, but there are undefined variables in the code behind
This is 4 channels 
![v1output_24bit](https://github.com/ValentinKoch/SVDNA/assets/114655828/c7473596-1399-4d0a-93c1-72d2bc6df720)
![v2patient2_raw0003](https://github.com/ValentinKoch/SVDNA/assets/114655828/845a7939-b223-4ca0-8e3d-5b6c0b44dcf2)

**Comment by ValentinKoch** [comment]
Hi @stonecropa 

as mentioned the implementation only works for images that have one channel. I updated the script to manually call .convert("L") which converts PIL images to grayscale. It works also with your sample images: 
<img width="1361" alt="Bildschirmfoto 2023-07-11 um 12 05 15" src="https://github.com/ValentinKoch/SVDNA/assets/55893735/8fe9b72a-d3b1-42ef-83aa-fff8630f58a1">

Let me know if you need additional assistance :) 

Best
Valentin
