### ISSUE TITLE
Why image size of 256x256? 

### ISSUE THREAD

**Issue by msseibel** [ValentinKoch/SVDNA#3]
Thank you for the great paper. I really love the simplicity of the approach.

Can you explain why you decided to resize the images to 256x256? As far as I read your paper and code, I understand that you load png files of the original files. Are these images already resampled to a common sampling rate? Further, I am confused that you resized the images without considering the aspect ratio and original size of the images. This results in distorted images which might hurt the downstream segmentation algorithm.

Did you explore other methods to match the image sizes? With other methods, I mean cropping of style images if they are larger than the source image or stitching style images if the the source image is larger than the style image.

Lastly, if I decide to use larger images, does it then make sense to use a larger number of singular values / vectors?

**Comment by ValentinKoch** [comment]
Hi, 
thanks a lot for your interest! This decision was mainly empirical, I tried also 512x512 but it worked slightly worse. The images I loaded had varying dimensionalities. It is true that resizing might distort images slightly but I would not be too worried about that: 
a) What is the alternative? If you train on one size and do inference in another, this will probably be even worse.
b) By looking at the original as well as reseized images from different devices I assumed that they all show roughly the same part of the retina, making different resolutions they provide arbitrary. I dont know if they actually show a square sized part. But you have to make some kind of decision in which resolution you want to input them and squaring worked well :) 

I think the important thing you have to ask yourself when rescaling images is: Would deomain experts be okay with this resolution and have the same performance? If yes I would always assume it is also fine to use as an input. If not it might even still be fine but I would not do it unless I have very good reason to do so. 

I did not explore things like cropping, you can try it but I would not expect it to work better, purely based on my feeling. 

If you decide to use larger images I  think it would make sense yes. Ultimately you would have to try a bit what works best and looks reasonably. 

Hope I could answer your questions, feel free to reach out again :)

Best
Valentin

**Comment by msseibel** [comment]
Thanks for the detailed answer. 

I suspected (without any empirical evidence) that different sampling rates contribute to the domain shift, so I decided to resize the images to the median sampling rate. Nonetheless, I agree with you that deep NN (be it CNNs or Transformers) should be able to work with differently scaled images.

Best
Marc

**Comment by ValentinKoch** [comment]
Hi Marc,

that could well be, honestly I do not know the technical details how these images are acquired. Best of luck for your work anyways!
Best
Valentin
