### ISSUE TITLE
What data augmentation was used after SVDNA?

### ISSUE THREAD

**Issue by msseibel** [ValentinKoch/SVDNA#4]
In the paper, you mentioned that data augmentation is applied after SVDNA. However, I can't find any details about the augmentation in this repository nor in the paper + supplementary. 

Did the data augmentation only involved geometric transformations or also transformations in the pixel value space?

Thanks in advance.

**Comment by ValentinKoch** [comment]
Hi, 

attached you find the augmentations I used. They were not extensively evaluated and same for all experiments. As far as I remember they were not influencing the performance a lot as long as I used reasonable parameters: 

```
augmentations = albu.Compose([
        albu.Rotate(p=0.3, limit=10),
        albu.RandomBrightnessContrast(brightness_limit=0.1, contrast_limit=0.1, p=0.15),
        albu.GaussNoise(p=0.1, var_limit=(10.0, 25.0)),
        albu.RandomGamma(gamma_limit=(90, 110), p=0.1),
        albu.GridDistortion(p=0.2),
        albu.ElasticTransform(p=0.2),
        albu.HorizontalFlip(p=0.5)])
```
Best
Valentin

**Comment by msseibel** [comment]
Thank you Valentin! This helps me to compare SVDNA with other Domain Generalization methods.

Best
Marc
